### ISSUE TITLE
Can you please publish version 1.2.0 to npm?

### ISSUE THREAD

**Issue by jric** [terrymorse58/serialize-anything#14]

**Comment by jric** [comment]
Hi Terry, alternatively, you could give "jric" permissions to publish to npm?  To unblock, I will publish serialize-anything-circular to npm for now.

**Comment by terrymorse58** [comment]
Hi,

I just invited "jrec" to publish serialize-anything on npmjs.

Thanks for helping out with serailize-anything.

- 
terry morse
***@***.***
https://terrymorse.com

On 2022-07-19 at 08:47:42, Joshua Richardson ***@***.***) wrote:

Hi Terry, alternatively, you could give "jric" permissions to publish to npm? To unblock, I will publish serialize-anything-circular to npm for now.

**Comment by terrymorse58** [comment]
I also added "jric" as a collaborator on the github repo.

- 
terry morse
***@***.***
https://terrymorse.com

On 2022-07-20 at 07:56:00, Terry Morse ***@***.***) wrote:

Hi,

I just invited "jrec" to publish serialize-anything on npmjs.

Thanks for helping out with serailize-anything.

- 
terry morse
***@***.***
https://terrymorse.com

On 2022-07-19 at 08:47:42, Joshua Richardson ***@***.***) wrote:

Hi Terry, alternatively, you could give "jric" permissions to publish to npm? To unblock, I will publish serialize-anything-circular to npm for now.

**Comment by jric** [comment]
Thanks, Terry.  Will be more convenient for me to help out.  But did you add "jrec" or "jric" on npmjs?  "jric" is my user name.

npm notice name:          serialize-anything                      
npm notice version:       1.2.1                                   
npm notice filename:      serialize-anything-1.2.1.tgz            
npm notice package size:  26.7 kB                                 
npm notice unpacked size: 158.9 kB                                
npm notice shasum:        c3d59c9892c78a7cad6a0f1d30f35e236a50f88f
npm notice integrity:     sha512-soiVdmuH2ltqD[...]fpr9ocZtnw98A==
npm notice total files:   20                                      
npm notice 
npm notice Publishing to https://registry.npmjs.org/
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/serialize-anything - You do not have permission to publish "serialize-anything". Are you logged in as the correct user?

**Comment by jric** [comment]
My npmjs profile:  https://www.npmjs.com/~jric

**Comment by jric** [comment]
My mistake.  I had to "accept" in email, then it worked.  Thanks!
